1. Create a function that takes dimensions as tuples e.g.(3, 3) and a numeric value and returns a
Numpy array of the given dimension filled with the given value e.g.: solve((3, 3), 5) will return
[
[5, 5, 5],
[5, 5, 5],
[5, 5, 5]
]

In [132]:
import numpy as np


u=np.full((3,3),5)
print(u)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


Create a method that takes n Numpy arrays of same dimensions sums them and return the
answer.

In [31]:
import numpy as np

arr1=np.array([1,2,3])
arr2=np.array([2,3,4])
y=arr1+arr2
print(y)

[3 5 7]


Given a 2 D Array of N X M Dimension, Write a function that accepts this array as well as two
numbers N and M. The method should return the top-left N X M sub matrix e.g:
[
[1, 2, 3],
[4, 5, 6],
[7, 8, 9],
]
top_left_sub_matrix (matrix, 2, 2) -> should return:
[
[1, 2]
[4, 5]
]

In [134]:
arr1=np.arange(1,10).reshape(3,3)
print(arr1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [135]:
print(arr1[:2, :2])

[[1 2]
 [4 5]]


In [92]:
print(arr1[2, :])

[7 8 9]


In [100]:
print(arr1[:, :2])

[[1 2]
 [4 5]
 [7 8]]


In [110]:
print(arr1[1,:])

[4 5 6]


4. Given a 2 D Array of N X M Dimension, Write a function that accepts this array as well as two
numbers N and M The method should return the bottom-right N X M sub matrix e.g.:
[
[1, 2, 3],
[4, 5, 6],
[7, 8, 9],
]
sub_matrix(matrix, 1, 1) -> should return : (Keep in mind these arrays are zero indexed)
[
[5, 6]
[8, 9]
]

In [136]:
arr1=np.arange(1,10).reshape((3,3))

In [119]:
print(arr1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [137]:
print(arr1[1:, 1:])

[[5 6]
 [8 9]]


In [145]:
print(arr1[:2,:2])

[[1 2]
 [4 5]]


Given a 1 D Numpy Array. Write a function that accepts this array as parameters. The method
should return a dictionary with 'mean' and 'std_dev' as key and array's mean and array's
standard deviation as values:
[1, 1, 1]
solution(arr) -> should return :
{'mean': 1.0, 'std_dev': 0.0}

In [1]:
arr1={'mean':1 ,'std_dev':1}

In [3]:
import numpy as np
def solution(arr):
    result={}
    result['mean']=np.mean(arr)
    result['std_dev']=np.std(arr)
    return resultS


In [4]:
arr=np.array([1,1,1])
result=solution(arr)
print(result)

{'mean': 1.0, 'std_dev': 0.0}
