In [3]:
import numpy as np

In [6]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

In [7]:
print(arr1)
print(arr2)

[1 2 3]
[4 5 6]


In [8]:
arr1*2

array([2, 4, 6])

In [9]:
arr3=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [15]:
np.full((2,3),1)

array([[1, 1, 1],
       [1, 1, 1]])

In [17]:
np.random.random((2,3))

array([[0.57533248, 0.76101696, 0.07383799],
       [0.49480757, 0.58022724, 0.09561296]])

In [34]:
a=np.arange(0,12)
print(a)
a.shape=(2,6)
print(a)
a.shape=(12)
print(a)
print(a.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
1


In [33]:
ar=np.array([1,2,3])
print(ar.ndim)

1


In [35]:
print(a.size)

12


In [37]:
a=np.array([1,2,3,4,5])
print(a.sum())

15


In [39]:
print(np.sum(a))

15


In [42]:
b=np.array([6,7,8,9,10])
c=a+b
print(c)

[ 7  9 11 13 15]


In [43]:
np.subtract(21,20)

1

In [45]:
np.subtract(b,a)

array([5, 5, 5, 5, 5])

In [46]:
print(np.sum((a,b),axis=0))

[ 7  9 11 13 15]


In [47]:
print(np.sum((a,b),axis=1))

[15 40]


In [ ]:
#other mathematical questions

In [ ]:
mul,div

In [48]:
np.exp(2)

7.38905609893065

In [49]:
np.sqrt(2)

1.4142135623730951

In [50]:
a=[3,4,5]
b=[3,3,3]
print(np.equal(a,b))

[ True False False]


In [53]:
a=[3,4,5]
b=[3,3,3]
c=[3,3,3]
print(np.array_equal(a,b))
print(np.array_equal(b,c))

False
True


In [ ]:
#aggregate function

In [62]:
a=[3,1,5]
b=[3,3,3]
c=[3,3,3]
np.sum(a)

9

In [57]:
np.min(a)

3

In [68]:
np.max(a)

5

In [60]:
np.mean(a)#average

3.0

In [63]:
np.median(a)#middle

3.0

In [66]:
np.corrcoef((a,b)) 

/home/mehnaz/.local/lib/python3.8/site-packages/numpy/lib/function_base.py:2854: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/home/mehnaz/.local/lib/python3.8/site-packages/numpy/lib/function_base.py:2855: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]


array([[ 1., nan],
       [nan, nan]])

In [67]:
np.std(a)

1.632993161855452

In [ ]:
#slicing and indexing

In [70]:
arr=np.array([1,2,3,4,5,6])
print(arr)

[1 2 3 4 5 6]


In [72]:
arr[:3]

array([1, 2, 3])

In [73]:
#2 dimensional array indexing

In [76]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [75]:
print(a.ndim)

2


In [77]:
a[0,:]

array([1, 2, 3])

In [78]:
a[0,0]

1

In [1]:
#concatenate

In [2]:
import numpy as np

In [3]:
a=[1,2,3,4,5]
b=[2,5,6,7,8]

In [6]:
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 2, 5, 6, 7, 8])

In [7]:
np.hstack((a,b)) #work similarly like concatenate

array([1, 2, 3, 4, 5, 2, 5, 6, 7, 8])

In [9]:
np.vstack((a,b))

array([[1, 2, 3, 4, 5],
       [2, 5, 6, 7, 8]])

In [11]:
np.column_stack((a,b))

array([[1, 2],
       [2, 5],
       [3, 6],
       [4, 7],
       [5, 8]])

In [12]:
x=np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [13]:
np.shape(x)

(16,)