In [1]:
# Import numpy by typing the following code in the notebook and run it by pressing shift
#+ enter

import numpy as np

In [5]:
#To create a 1d numpy array, pass a 1d list into np.array method


import numpy as np
list1=[1,2,3,4,5]
array1=np.array(list1)
print(array1)

[1 2 3 4 5]


In [10]:
#To create a 2d numpy array, pass a 2d list into np.array method.
m=np.array([[1,2,3],[4,5,6]])
print(m)


[[1 2 3]
 [4 5 6]]
