Q1. For a given numpy array, how will you change the dimensions to 5 using the
existing parameters in the numpy array.
my_array = numpy.array([[[[1,3,4]]]])

In [ ]:
import numpy

my_array = numpy.array([[[[1,3,4]]]])

In [ ]:
numpy.array(my_array,ndim=5)

TypeError: ignored

For the given numpy arrays, Array1 and Array2, what will be the dot product for
the same. Array1 = array([[1, 2, 3], [4, 5, 6]])
Array2 = array([[2, 3],[3, 2]])

In [ ]:
import numpy as np

Array1 = np.array([[1, 2, 3],[4, 5, 6]])
Array2 = np.array([[2, 3],[3, 2]])
np.dot(Array1,Array2)

ValueError: ignored

Q3. In a given numpy array, using the slicing operations print the reverse of the
array.
array = np.array([10,3,1,203,404,204,20,302,30,402,192])

In [ ]:
import array
array. array = np.array([10,3,1,203,404,204,20,302,30,402,192])

In [ ]:
array.array[::-1]

array([192, 402,  30, 302,  20, 204, 404, 203,   1,   3,  10])

Q4. What is the output of the below code:
a = [[1, 0], [0, 1]]
b = [[4, 1], [2, 2]]
np.dot(a, b)

In [ ]:
a = [[1, 0], [0, 1]]
b = [[4, 1], [2, 2]]
np.dot(a, b)

array([[4, 1],
       [2, 2]])

Q5. What is the output of the following code:
a = np.arange(3*4*5*6).reshape((3,4,5,6))
b = np.arange(3*4*5*6)[::-1].reshape((5,4,6,3))
np.dot(a, b)[2,3,2,1,2,2]

In [ ]:
a = np.arange(3456).reshape((3,4,5,6))
b = np.arange(3456)[::-1].reshape((5,4,6,3))
np.dot(a, b)[2,3,2,1,2,2]

ValueError: ignored

Q6. What will be output for the following code?
import numpy as np
a = np.array([3, 7, 32], dtype = complex)
print(a)

In [ ]:
import numpy as np
a = np.array([3, 7, 32], dtype = complex)
print(a)

[ 3.+0.j  7.+0.j 32.+0.j]


Q7. How to replace all values greater than a given value with a given cutoff? For
example: In array ‘ar1’, replace all values greater than 30 to 30 and less than 10 to 10.
Input:
np.random.seed(100)
ar1 = np.random.uniform(1,50, 20)

In [ ]:
np.random.seed(100)
ar1 = np.random.uniform(1,50, 20)
np.where(a < 10, 10, np.where(a > 30, 30, a))

array([10.+0.j, 10.+0.j, 30.+0.j])

array([27.62684215, 14.64009987, 21.80136195, 42.39403048,  1.23122395,
        6.95688692, 33.86670515, 41.466785  ,  7.69862289, 29.17957314,
       44.67477576, 11.25090398, 10.08108276,  6.31046763, 11.76517714,
       48.95256545, 40.77247431,  9.42510962, 40.99501269, 14.42961361])

Q8. For a given numpy array, how are you going to insert a new value at the specified
position? array = np.array([10,3,1,203,404,204,20,302,30,402,192])
Elem_to_be_inserted = [1,2,3,4]
The position to be inserted at = before 404

In [2]:
import numpy as np

array = np.array([10,3,1,203,404,204,20,302,30,402,192])
array2=np.array([1,2,3,4])

In [3]:
np.insert(array,4,array2)

array([ 10,   3,   1, 203,   1,   2,   3,   4, 404, 204,  20, 302,  30,
       402, 192])

Create a 3x3 matrix using numpy, and all the values of the matrix must be a constant k.

In [6]:
np.full((3,3),'k')

array([['k', 'k', 'k'],
       ['k', 'k', 'k'],
       ['k', 'k', 'k']], dtype='<U1')

For the given python code that implements bubble sort, what will be the output for the
given numpy array


In [16]:
import numpy
def bub_sort(array):
  for i in range(0, len(array)):
      for j in range(0, len(array) - i - 1):
        if array[j] < array[j + 1]:
          temp = array[j]
          array[j] = array[j + 1]
          array[j+1] = temp
          return array
my_array = numpy.array([20,14,25,16,45,60,12,9])
print(array)

[ 10   3   1 203 404 204  20 302  30 402 192]


For a given numpy array of the shape (2,5) ,How will you reshape the array in the shape (5,2).

In [20]:
one=np.arange(0,10).reshape(2,5)
one.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

Q12. What will be the shape of the sample numpy array after flattening it?
Sample = numpy.array([[1,2],[3,4],[5,6],[7,8]])

In [21]:
Sample = np.array([[1,2],[3,4],[5,6],[7,8]])

In [23]:
Sample.shape

(4, 2)

In [32]:
np.hstack(Sample)

array([1, 2, 3, 4, 5, 6, 7, 8])

Q13. In the given array, how can we get the following output - array([2, 5,
8]). Sample = numpy.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])

In [33]:
 Sample = numpy.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])

In [37]:
Sample[:3,1]

array([2, 5, 8])

Q14. Given two numpy arrays, we will perform Horizontally stack the given arrays array1 and
array2. What will be the output of the above operation? The sample arrays are as follows.
Array1 = numpy.arange(20,2)
Array2 = numpy.array([1,2,3,4,5,6,7,8,9,10])

In [44]:
Array1 = numpy.arange(20,2)
Array2 = numpy.array([1,2,3,4,5,6,7,8,9,10])
np.hstack((Array1,Array2))


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Q15. For the given arrays, array1 and array2, if we stack the two arrays row wise, what will be
the output?
array1 = np.array([[1,2],[3,4]])
array2 = np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])

In [47]:
array1 = np.array([[1,2],[3,4]])
array2 = np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])
np.vstack((array1,array2))

array([[ 1,  2],
       [ 3,  4],
       [ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

Q16. For the given arrays, array1 and array2, if we stack the two arrays column wise, what
will be the output?
array1 = np.array([[1,2],[3,4]])
array2 = np.array([[5,6],[7,8]])

In [49]:
array1 = np.array([[1,2],[3,4]])
array2 = np.array([[5,6],[7,8]])
np.hstack((array1,array2))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

Q17. Given two vectors A and B, find the cross product between the two
vectors. A = numpy.array([[4],[12],[29]])
B = numpy.array([[13],[21],[4]])

In [62]:
A = np.array([[[4],[12],[29]]])
B = np.array([[[13],[21],[4]]])



In [60]:
np.cross(A,B)

ValueError: ignored

Q18. Given two vectors A and B, find the correlation coefficient of the following
vectors. A = numpy.array([1,3,5,7,9,11,13,15,17,19,21,23,25])
B = numpy.array([0,2,4,6,8,10,12,14,16,18,20, 22, 24])

In [66]:
import numpy as np

A = numpy.array([1,3,5,7,9,11,13,15,17,19,21,23,25])
B = numpy.array([0,2,4,6,8,10,12,14,16,18,20, 22, 24])
np.corrcoef(A,B)

array([[1., 1.],
       [1., 1.]])

Q19. Create a nested numpy array from a given dictionary data.
sample = {1: [1,2],
2: [[1],[2]],
3: [[1,2], [3,4], [4,5]],
4: [1],
5: [1,2,3,4,5]}

In [67]:
sample = {1: [1,2], 2: [[1],[2]], 3: [[1,2], [3,4], [4,5]], 4: [1], 5: [1,2,3,4,5]}

In [68]:
sample

{1: [1, 2],
 2: [[1], [2]],
 3: [[1, 2], [3, 4], [4, 5]],
 4: [1],
 5: [1, 2, 3, 4, 5]}

Q20. A 2-dimensional array with 3 rows and 3 columns containing random numbers from 1
to 9 is given as - arr1= np.array([[3,2,1],[6,4,5],[8,7,9]])
Find the difference between the maximum element across the columns and the minimum
element across the rows.

In [70]:
arr1= np.array([[3,2,1],[6,4,5],[8,7,9]])
np.max(arr1,axis=1)

array([3, 6, 9])

In [71]:
np.min(arr1,axis=0)

array([3, 2, 1])