Numpy is a python library used for mathematical computations.


Numpy was created in year 2005 by travis oliphant

Numpy stands for numerical Python


Numpy is faster as compared to list in python.


Numpy arrays are stored at one continuous place in memory unlike list, due to which it is
faster than lists.


Numpy is a pyhton library and is partially eritten in Python, but the parts that require fast computations are written in C or C++.

In [1]:
pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
import numpy as np


# np is a pseudo name or a alias name,alternate name for referring to the same thing

In [3]:
# USES OF NUMPY:

# 1) Aithmetic operations.
# 2) Statistical operations.
# 3) stacking.
# 4) searching, sorting and counting.

In [4]:
print(np.__dict__)


{'__name__': 'numpy', '__doc__': '\nNumPy\n=====\n\nProvides\n  1. An array object of arbitrary homogeneous items\n  2. Fast mathematical operations over arrays\n  3. Linear Algebra, Fourier Transforms, Random Number Generation\n\nHow to use the documentation\n----------------------------\nDocumentation is available in two forms: docstrings provided\nwith the code, and a loose standing reference guide, available from\n`the NumPy homepage <https://www.scipy.org>`_.\n\nWe recommend exploring the docstrings using\n`IPython <https://ipython.org>`_, an advanced Python shell with\nTAB-completion and introspection capabilities.  See below for further\ninstructions.\n\nThe docstring examples assume that `numpy` has been imported as `np`::\n\n  >>> import numpy as np\n\nCode snippets are indicated by three greater-than signs::\n\n  >>> x = 42\n  >>> x = x + 1\n\nUse the built-in ``help`` function to view a function\'s docstring::\n\n  >>> help(np.sort)\n  ... # doctest: +SKIP\n\nFor some object

In [5]:
print(np.__version__)

1.22.4


In [6]:
# The array object in python is called ndarry

In [7]:
arr = np.array((1,2,4,5))

In [8]:
print(arr)

[1 2 4 5]


In [13]:
# Dimensions in Array:
# depth of an array

# 0 dimensional array:0-D arrays are the elemsnts in an array. Each value in an array is a 0-D array.

arr = np.array(45)
arr


array(45)

In [14]:
# 1-D array: an array that has 0-D arrays as its element.

arr1 = np.array([1,2,3,4,5])

In [15]:
arr1

array([1, 2, 3, 4, 5])

In [16]:
# 2-D Arrays: stored in a form of row and columns or represents a matrix.


arr2 = np.array([[1,2,3,4,5],[1,2,3,4,5]])

In [17]:
print(arr2)

[[1 2 3 4 5]
 [1 2 3 4 5]]


In [18]:
print(arr.ndim)
print(arr1.ndim)
print(arr2.ndim)

0
1
2


In [20]:
print(arr.shape)
print(arr1.shape)
print(arr2.shape)

()
(5,)
(2, 5)


In [22]:
arr3=np.array([[1,2,3,4,5]])
arr3.ndim


2

In [ ]:

# create a matrix full of 1s and 5s
# create a matrix full of zeros
# create a matrix (4,5) and then tell in which shapes it can be reshaped

In [31]:
a = np.ones((5,3),dtype="int")

In [32]:
type(a)

numpy.ndarray

In [33]:
a

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [34]:
a.dtype

dtype('int64')

In [36]:
b = np.ones((5,3),dtype="int")*5

In [37]:
c = np.full((5,3),5)

In [38]:
c

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [39]:
c1 = np.full((5,3),1)

In [40]:
c1

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [47]:
d = np.identity(2,dtype="int")

In [48]:
d

array([[1, 0],
       [0, 1]])

In [49]:
e = np.full((4,5),10)

In [50]:
e

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [51]:
e.shape

(4, 5)

In [52]:
e.ndim

2

In [53]:
e1 = np.full((4,5),10).reshape(2,10)

In [54]:
e1

array([[10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10]])

In [55]:
#How can you reverse a NumPy array?

In [56]:
arr = np.array([1,2,3,4,5])

reverse_arr = arr[::-1]

In [57]:
reverse_arr

array([5, 4, 3, 2, 1])

In [59]:
arr1 = np.array([1,2,3,4,5])

reverse_arr = np.flip(arr1)
reverse_arr

array([5, 4, 3, 2, 1])

In [60]:
#How do you count the frequency of a given positive value appearing in the NumPy array?

In [68]:
a = np.array([1,2,3,4,5,6,7,8,9,10,1,2,3,4,5,6,7,8,9,10,1,1,1,1,2,3,3,3,6,7,8,0,0,0,-1,-1,-1])

In [69]:
print(np.count_nonzero(a == 0))

3


In [70]:
b = np.sort(a)

In [71]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10,  1,  2,  3,  4,  5,  6,  7,
        8,  9, 10,  1,  1,  1,  1,  2,  3,  3,  3,  6,  7,  8,  0,  0,  0,
       -1, -1, -1])

In [72]:
b

array([-1, -1, -1,  0,  0,  0,  1,  1,  1,  1,  1,  1,  2,  2,  2,  3,  3,
        3,  3,  3,  4,  4,  5,  5,  6,  6,  6,  7,  7,  7,  8,  8,  8,  9,
        9, 10, 10])

In [73]:
arr = np.array([1,2,3,4,5,4,4])

new_arr = np.where(arr==4)
new_arr

(array([3, 5, 6]),)

In [74]:
e1 = np.full((4,5),10)

In [75]:
e1

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [76]:
a = np.transpose(e1)

In [77]:
a

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [81]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [79]:
arr1 = np.transpose(arr)

In [80]:
arr1

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [82]:
arr.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])