In [30]:
#for slicing in matrix

In [31]:
import numpy as np

In [2]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [3]:
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
arr[0,:]

array([1, 2, 3])

In [14]:
arr[:2,1:]

array([[2, 3],
       [5, 6]])

In [18]:
arr[:1,1:]

array([[2, 3]])

In [19]:
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [20]:
arr[0:2,1:]

array([[2, 3],
       [5, 6]])

In [21]:
arr[:2,:2]

array([[1, 2],
       [4, 5]])

In [22]:
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [23]:
arr[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
arr[1:,:]

array([[4, 5, 6],
       [7, 8, 9]])

In [25]:
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [29]:
arr[1:2,:2]

array([[4, 5]])

In [33]:
arr[:2,1:]

array([[2, 3],
       [5, 6]])